rsion: '3.8'
services:
  postgres-db:
    image: postgres:16.0-alpine
    environment:
      - POSTGRES_USER=habr_admin
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=habr_db
    ports:
      - '5436:5432'
    volumes:
      - ./data:/var/lib/postgresql/data