spring:
  application:
    name: habr-demo
  datasource:
    url: jdbc:postgresql://localhost:5436/habr_db
    username: habr_admin
    password: qwerty123
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        default_schema: ${default-schema.name}
  liquibase:
    change-log: classpath:db/changelog/master.xml
    enabled: true
    contexts: prod
    default-schema: ${default-schema.name}

mybatis:
  config-location: classpath:mybatis/config.xml
  mapper-locations: classpath:mybatis/mappers/*.xml

default-schema:
  name: habr_api