package com.chvs.habrdemo.core.model.profile;

import lombok.RequiredArgsConstructor;

import static com.chvs.habrdemo.core.model.profile.GeneralSpeciality.*;

@RequiredArgsConstructor
enum Speciality {

    SOFTWARE_DEVELOPER("Десктоп разработчик", SOFTWARE_DEVELOPMENT),
    BACKEND_DEVELOPER("Бэкенд разработчик", SOFTWARE_DEVELOPMENT),
    FRONTEND_DEVELOPER("Фронтенд разработчик", SOFTWARE_DEVELOPMENT),
    FULLSTACK_DEVELOPER("Фулстек разработчик", SOFTWARE_DEVELOPMENT),
    MOBILE_APPLICATION_DEVELOPER("Разработчик мобильных приложений", SOFTWARE_DEVELOPMENT),
    GAME_DEVELOPER("Разработчик игр", SOFTWARE_DEVELOPMENT),
    EMBEDDED_SOFTWARE_ENGINEER("Инженер встраиваемых систем", SOFTWARE_DEVELOPMENT),
    SYSTEM_SOFTWARE_ENGINEER("Системный инженер", SOFTWARE_DEVELOPMENT),
    APPLICATION_DEVELOPER("Разработчик приложений", SOFTWARE_DEVELOPMENT),
    SOFTWARE_ARCHITECT("Архитектор программного обеспечения", SOFTWARE_DEVELOPMENT),
    RELEASE_MANAGER("Релиз менеджер", SOFTWARE_DEVELOPMENT),
    DATABASE_DEVELOPER("Разработчик баз данных", SOFTWARE_DEVELOPMENT),
    WEB_DEVELOPER("Веб-разработчик", SOFTWARE_DEVELOPMENT),
    HTML_CODING("HTML-верстальщик", SOFTWARE_DEVELOPMENT),
    ONE_C_DEVELOPER("Программист 1С", SOFTWARE_DEVELOPMENT),
    DATABASE_ARCHITECT("Архитектор баз данных", SOFTWARE_DEVELOPMENT),
    OTHER_SOFTWARE_DEVELOPMENT_SPECIALITY("Другое", SOFTWARE_DEVELOPMENT),
    TEST_AUTOMATION_ENGINEER("Инженер по автоматизации тестирования", QUALITY_ASSURANCE),
    SOFTWARE_PERFORMANCE_ENGINEER("Инженер по производительности", QUALITY_ASSURANCE),
    MANUAL_TEST_ENGINEER("Инженер по ручному тестированию", QUALITY_ASSURANCE),
    QUALITY_ASSURANCE_ENGINEER("Инженер по обеспечению качества", QUALITY_ASSURANCE),
    QUALITY_ASSURANCE_ANALYST("Аналитик по обеспечению качества", QUALITY_ASSURANCE),
    QUALITY_ASSURANCE_MANAGER("Менеджер по обеспечению качества", QUALITY_ASSURANCE),
    QUALITY_ASSURANCE_DIRECTOR("Директор по обеспечению качества", QUALITY_ASSURANCE),
    UX_TESTER("UX-тестировщик", QUALITY_ASSURANCE),
    OTHER_QUALITY_ASSURANCE_SPECIALITY("Другое", QUALITY_ASSURANCE),
    SYSTEM_ADMINISTRATION("Системный администратор", ADMINISTRATION),
    SERVER_ADMINISTRATOR("Администратор серверов", ADMINISTRATION),
    DATABASE_ADMINISTRATOR("Администратор баз данных", ADMINISTRATION),
    NETWORK_ENGINEER("Сетевой инженер", ADMINISTRATION),
    DEVOPS("DevOps-инженер", ADMINISTRATION),
    SITE_ADMINISTRATOR("Администратор сайта", ADMINISTRATION),
    ML_OPS("MLOps-инженер", ADMINISTRATION),
    SITE_RELIABILITY_ENGINEER("Инженер по доступности сервисов", ADMINISTRATION),
    WIRELESS_SYSTEM_ENGINEER("Инженер по беспроводным системам", ADMINISTRATION),
    OTHER_ADMINISTRATION_SPECIALITY("Другое", ADMINISTRATION),
    UI_UX_DESIGNER("UI/UX дизайнер", DESIGN),
    WEB_DESIGNER("Веб дизайнер", DESIGN),
    APPLICATION_DESIGNER("Дизайнер приложений", DESIGN),
    GAME_DESIGNER("Дизайнер игр", DESIGN),
    DESIGNER_ILLUSTRATOR("Дизайнер иллюстратор", DESIGN),
    MOTION_DESIGNER("Моушен дизайнер", DESIGN),
    THREE_D_MODELER("3d моделлер", DESIGN),
    GRAPHIC_DESIGNER("Графический дизайнер", DESIGN),
    ART_DIRECTOR("Арт директор", DESIGN),
    COMPUTER_GRAPHICS_ARTIST("Художник компьютерной графики", DESIGN),
    PRODUCT_DESIGNER("Продуктовый дизайнер", DESIGN),
    OTHER_DESIGN_SPECIALITY("Другое", DESIGN),
    PROJECT_MANAGER("Менеджер проекта", MANAGEMENT),
    PROJECT_DIRECTOR("Директор проекта", MANAGEMENT),
    COMMUNITY_MANAGER("Менеджер сообщества", MANAGEMENT),
    PROGRAM_MANAGE("Программный менеджер", MANAGEMENT),
    DELIVERY_MANAGER("Деливери-менеджер", MANAGEMENT),
    OTHER_MANAGEMENT_SPECIALITY("Другое", MANAGEMENT),
    SYSTEMS_ANALYST("Системный аналитик", ANALYTICS),
    BUSINESS_ANALYST("Бизнес-аналитик", ANALYTICS),
    DATA_ANALYST("Аналитик по данным", ANALYTICS),
    DATA_ENGINEER("Инженер по данным", ANALYTICS),
    SOFTWARE_ANALYST("Программный аналитик", ANALYTICS),
    PRODUCT_ANALYST("Продуктовый аналитик", ANALYTICS),
    MOBILE_ANALYST("Аналитик мобильных приложений", ANALYTICS),
    GAME_ANALYST("Гейм-аналитик", ANALYTICS),
    OTHER_ANALYTICS_SPECIALITY("Другое", ANALYTICS),
    TECHNICAL_SUPPORT_MANAGER("Менеджер технической поддержки", SUPPORT),
    TECHNICAL_SUPPORT_DIRECTOR("Директор технической поддержки", SUPPORT),
    CUSTOMER_SERVICE_MANAGER("Менеджер по обслуживанию клиентов", SUPPORT),
    TECHNICAL_SUPPORT_ENGINEER("Инженер технической поддержки", SUPPORT),
    TECHNICAL_SUPPORT_ANALYST("Аналитик технической поддержки", SUPPORT),
    MODERATOR("Модератор", SUPPORT),
    OTHER_SUPPORT_SPECIALITY("Другое", SUPPORT),
    MARKETING_MANAGER("Менеджер по маркетингу", MARKETING),
    MARKETING_DIRECTOR("Директор по маркетингу", MARKETING),
    SEO_SPECIALIST("SEO-специалист", MARKETING),
    SMM_SPECIALIST("SMM-специалист", MARKETING),
    PR_MANAGER("PR-менеджер", MARKETING),
    OTHER_MARKETING_SPECIALITY("Другое", MARKETING),
    ACCOUNT_MANAGER("Менеджер по работе с клиентами", SALES),
    ACCOUNT_DIRECTOR("Директор по работе с клиентами", SALES),
    SALES_MANAGER("Менеджер по продажам", SALES),
    SALES_DIRECTOR("Директор по продажам", SALES),
    SALES_ANALYST("Аналитик продаж", SALES),
    OTHER_SALES_SPECIALITY("Другое", SALES),
    HR_MANAGER("Менеджер по персоналу", HR),
    RECRUITMENT_MANAGER("Менеджер по найму", HR),
    RECRUITMENT_DIRECTOR("Директор по найму", HR),
    HR_ANALYST("Аналитик по персоналу", HR),
    OTHER_HR_SPECIALITY("Другое", HR),
    OFFICE_MANAGER("Офис менеджер", OFFICE),
    ACCOUNTANT("Бухгалтер", OFFICE),
    LAWYER("Юрист", OFFICE),
    OTHER_OFFICE_SPECIALITY("Другое", OFFICE),
    SECURITY_ADMINISTRATOR("Администратор защиты", INFORMATION_SECURITY),
    PENTESTER("Пентестер", INFORMATION_SECURITY),
    REVERSE_ENGINEER("Специалист по реверс-инжинирингу", INFORMATION_SECURITY),
    SECURITY_ENGINEER("Инженер по безопасности", INFORMATION_SECURITY),
    INFORMATION_SECURITY_ARCHITECT("Архитектор информационной безопасности", INFORMATION_SECURITY),
    OTHER_INFORMATION_SECURITY_SPECIALITY("Другое", INFORMATION_SECURITY),
    DATA_SCIENTIST("Ученый по данным", ARTIFICIAL_INTELLIGENCE),
    ML_ENGINEER("ML разработчик", ARTIFICIAL_INTELLIGENCE),
    PROMT_ENGINEER("Промт-инженер", ARTIFICIAL_INTELLIGENCE),
    OTHER_ARTIFICIAL_INTELLIGENCE_SPECIALITY("Другое", ARTIFICIAL_INTELLIGENCE);

    private final String description;
    private final GeneralSpeciality generalSpeciality;
}
